apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-deployment
  namespace: liatrio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: liatrio
  template:
    metadata:
      labels:
        app: liatrio
    spec:
      containers:
        - name: liatrio
          image: 218920203343.dkr.ecr.us-east-1.amazonaws.com/liatrio
          ports:
            - containerPort: 5000
