name: Helm Deployment

on:
  workflow_run:
    workflows: ["Deployment"]
    types:
      - completed

jobs:
  helm_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Deploy Helm Chart
      working-directory: helm
      run: |
        helm upgrade --install liatrio ./my-helm-chart
