name: Deployment

on:
  push:
    branches:
      - master  # Run on push to the master branch

env:
  
  AWS_REGION : "us-east-1" #Change to reflect your Region

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
        terraform_wrapper: false

      - name: Assume AWS IAM Role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::218920203343:role/github
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1  # Replace with your desired AWS region

      - name: Initialize Terraform
        run: terraform init 
        working-directory: terraform/

      - name: Plan changes
        run: terraform plan -var-file=terraform.tfvars 
        working-directory: terraform/

      - name: Apply changes
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -var-file=terraform.tfvars 
        working-directory: terraform/
      
      - name: Capture Kubeconfig
        run: |
          # Get the EKS cluster name from the Terraform output
          EKS_CLUSTER_NAME=$(terraform output  cluster_name)
          
          # Generate and capture kubeconfig
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region us-east-1 --kubeconfig eks-config
          echo "KUBECONFIG=$(cat eks-config)" >> $GITHUB_ENV
        working-directory: terraform/
      
      - name: Capture ECR Image URL
        id: tf
        run: |
          ECR_IMAGE_URL=$(terraform output ecr_image_url)
          echo "ECR_IMAGE_URL=$ECR_IMAGE_URL" >> $GITHUB_ENV
        working-directory: terraform/

      - name: Update Deployment YAML
        run: |
          sed -i "s|image: .*|image: $ECR_IMAGE_URL|" deployment.yaml
        working-directory: kubernetes/templates/

      
      - name: Get AWS Account ID
        id: get-account-id
        run: echo "::set-output name=ACCOUNT_ID::$(aws sts get-caller-identity --query 'Account' --output text)"

      
      - name: Build Docker image
        run: docker build -t liatrio .
        working-directory: app/
  

      - name: Log into Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.get-account-id.outputs.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com 


      - name: Tag Docker image
        run: docker tag liatrio ${{ steps.get-account-id.outputs.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/liatrio

      - name: Push Docker image to ECR
        run: docker push ${{ steps.get-account-id.outputs.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/liatrio


      - name: Deploy Helm Chart
        run: |
          helm upgrade --install liatrio ./kubernetes



