name: Terraform Automation

on:
  push:
    paths:
      - 'terraform/**'
    branches:
      - master
    

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init terraform

    - name: Plan changes
      run: terraform plan -var-file=terraform/terraform.tfvars terraform

    - name: Apply changes
      run: terraform apply -auto-approve -var-file=terraform/terraform.tfvars terraform
